---
- name: Reload wireguard
  ansible.builtin.service:
    name: "wg-quick@{{ wg_int['name'] }}"
    state: 'reloaded'
  register: 'reloaded_wireguard'
  until: reloaded_wireguard is successful
  retries: 3
  delay: 5
  no_log: "{{ wireguard__no_log }}"
  loop: "{{ wireguard__interfaces__merged }}"
  loop_control:
    loop_var: 'wg_int'
