---
- name: SSH -- enable Service, start and reload
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true

- name: SSH -- Update SSH config
  lineinfile:
    dest: "{{ ssh__config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication {{ ssh__password_authentication }}"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin {{ ssh__permit_root_login }}"
    - regexp: "^Port"
      line: "Port {{ ssh__port }}"
    - regexp: "^UseDNS"
      line: "UseDNS {{ ssh__usedns }}"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords {{ ssh__permit_empty_password }}"
    - regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication {{ ssh__gss_api_authentication }}"
    - regexp: "^X11Forwarding"
      line: "X11Forwarding {{ ssh__x11_forwarding }}"
  notify:
    - Restart SSH

- name: SSH -- Add allowed users
  lineinfile:
    dest: "{{ ssh__config_path }}"
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ssh__allowed_users | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: ssh__allowed_users | length > 0
  notify:
    - Restart SSH

- name: SSH -- Add allowed groups
  lineinfile:
    dest: "{{ ssh__config_path }}"
    regexp: '^AllowGroups'
    line: "AllowGroups {{ ssh__allowed_groups | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: ssh__allowed_groups | length > 0
  notify:
    - Restart SSH
