---
- name: sudo -- Add passwordless sudoers user
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ sudo__sudoers_passwordless }}"
  when: sudo__sudoers_passwordless | length > 0

- name: sudo -- Add passworded sudoers user
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ sudo__sudoers_passworded }}"
  when: sudo__sudoers_passworded | length > 0